project_id = "wppdrxuqvolqnsojubsp"

[functions.generate-notes]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.check-access]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.submit-rating]
verify_jwt = false
